### PR TITLE
Migrate CE 0340 Ge Hong & Bao Gu.md

### PR DESCRIPTION
**Pull request by Ismael-KG**
@yochannah - will there be a way to search stories by tag?

Also, I just realised categories aren't showing, so I am trying "".

### CODE REVIEW

**Comment by yochannah** [comment]
There _can_ be a way to do tags, it'll just need a little fiddling.

**Comment by Ismael-KG** [comment]
oh no! The preview won't show!

**Comment by Ismael-KG** [comment]
Okay, whitespace gone, now testing "" around the category again.

**Comment by Ismael-KG** [comment]
Category fix no.2: change spaces to hyphens. Now testing.

**Comment by Ismael-KG** [comment]
Incredible, now using the correct categories as per https://github.com/Ismael-KG/A-History-of-Research-Ethics/issues/37#issuecomment-988001661

**Pull request merged**
